server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8085

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
 # instance:
 #   prefer-ip-address: true
 # client:
  #  fetch-registry: true
   # register-with-eureka: true
    #server-url:
     # defaultZone: http://localhost:8761/eureka